### ISSUE TITLE
Issues with Home Assistant 2024.2

### ISSUE THREAD

**Issue by guarddog13** [toverainc/willow-autocorrect#4]
HA changed the way they respond to unknown commands. This has made it so that using WAC as a fallback to an AI or Google Assistant is no longer working.

**Comment by nikito** [comment]
This has been fixed in wac, please pull latest and rebuild. 🙂

**Comment by stintel** [comment]
88267a87b7156ad8f9cd9631ab4d8be3796859ae

**Comment by guarddog13** [comment]
This is still an issue periodically. If HA responds with "Sorry I am not aware of any device called......." then that's all that is returned via Willow and not forwarded as an error as it should be.

**Comment by nikito** [comment]
Did you stop wac, pull, rebuild via utils.sh, then rerun?
